### PR TITLE
Rockets branch

### PR DESCRIPTION
**Pull request by shogof**
### Pull Request Description

**Overview:**
This pull request introduces significant improvements to the Rockets feature in the Space Travelers Hub project. It enhances state management for rocket reservations and improves navigation, ensuring a smoother user experience. This is my first collaborative project, and I’m excited to contribute to the team! 🌟

**Changes Made:**
- **State Management:**
  - Updated the `RocketsSlice` to maintain rocket reservation states when fetching new data from the SpaceX API. 🛰️
  - Ensured that existing reservations persist, preventing data loss during updates.

- **Navigation Improvements:**
  - Resolved issues with page reloads when switching between different components, allowing for seamless navigation within the application. 🔄

- **Code Quality:**
  - Refactored arrow functions to comply with ESLint rules regarding parameter parentheses, improving overall code quality. ✅

I kindly appreciate your time and would love any feedback or suggestions you might have to improve this feature further. Thank you for your support and guidance! 🙏

### CODE REVIEW

**Comment by shogof** [comment]
@royajamal @Marwa-Sadat 
---
Hi team! 😊

I’ve just submitted a pull request for the Rocket page 🚀. When you have a moment, could you please take a look and share your feedback?

Thanks so much, and best of luck with your work! 🍀
Cheers,  
Shogofa Muradi

**Comment by royajamal** [comment]
Hi @shogof 🙋‍♀️,
Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊
Well Done great design Implemented. 🎯🎉👍
Status: Approved ✅
Highlights 😊
💯 The implementation of a great design is superb.
✔️ You've established a professional repository with your project's name.
✔️ You've mastered Gitflow by making the development branch your default and diligently committingy our work on a feature branch. 🌟
✔️ Add this to ensuring commits are more descriptive and follow a logical sequence.
✔️ Setup the linters correctly (You added the correct linters config into your project according tot he language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Build  Space Travelers Hub project task and committed using the command line
✔️ You've initiated the pull request by submitting a link for review from your feature branch to the- development branch.
✔️ You have followed and completed the Space Travelers Hub and all requirements.
✔️ You've enriched your PR with a detailed description highlighting the features and improvementsi ncorporated in this pull request. 📝
✔️ Your code is clean
✔️ Your repo has a professional README.md file
✔️ Your design is responsive
✔️ Users can easily view and interact with the rockets list. The functionality of reserving or canceling a reservation is straightforward and easy to understand.
✔️ The rockets’ status (Reserved/Not Reserved) is clearly visible, ensuring users are aware of their actions and their consequences.
C heers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread ifs omething is not 100% clear.

**Comment by Marwa-Sadat** [comment]
🚀 Excellent Work on the Space Travelers’ Hub!

Hey Shogof 👋

I’ve reviewed this pull request, and I must say, the implementation is impressive! Here are a few highlights:

	1.	✔ Code Quality: The code is well-organized and easy to follow. I appreciate the attention to detail in adhering to the project structure. 🏗
	2.	✔ Functionality: The added features integrate seamlessly with the existing codebase, providing a smooth user experience. The responsiveness is spot-on, especially across different viewports. 📱💻
	3.	✔ Documentation: Clear and concise explanations in the code comments make it easy for future contributors to understand. 📄

Suggestions for Improvement:

	1.	✔ Error Handling: It would be beneficial to add more comprehensive error handling, especially when dealing with API requests. This ensures a more robust user experience when network issues arise. 🌐
	2.	✔ Optimization: Consider optimizing some of the components for performance, particularly in rendering large datasets. Using React’s memo or lazy loading where appropriate can improve efficiency. ⚡

Overall, fantastic job! Keep up the great work. 🎉


-Marwa Sadat-

**Comment by Marwa-Sadat** [comment]
🚀 Excellent Work on the Space Travelers’ Hub!

Hey Shokoof , 👋

I’ve reviewed this pull request, and I must say, the implementation is impressive! Here are a few highlights:

	1.	✔ Code Quality: The code is well-organized and easy to follow. I appreciate the attention to detail in adhering to the project structure. 🏗
	2.	✔ Functionality: The added features integrate seamlessly with the existing codebase, providing a smooth user experience. The responsiveness is spot-on, especially across different viewports. 📱💻
	3.	✔ Documentation: Clear and concise explanations in the code comments make it easy for future contributors to understand. 📄

Suggestions for Improvement:

	1.	✔ Error Handling: It would be beneficial to add more comprehensive error handling, especially when dealing with API requests. This ensures a more robust user experience when network issues arise. 🌐
	2.	✔ Optimization: Consider optimizing some of the components for performance, particularly in rendering large datasets. Using React’s memo or lazy loading where appropriate can improve efficiency. ⚡

Overall, fantastic job! Keep up the great work. 🎉


Marwa Sadat

**Comment by Marwa-Sadat** [comment]
🚀 Excellent Work on the Space Travelers’ Hub!

Hey Shokoof , 👋

I’ve reviewed this pull request, and I must say, the implementation is impressive! Here are a few highlights:

	1.	✔ Code Quality: The code is well-organized and easy to follow. I appreciate the attention to detail in adhering to the project structure. 🏗
	2.	✔ Functionality: The added features integrate seamlessly with the existing codebase, providing a smooth user experience. The responsiveness is spot-on, especially across different viewports. 📱💻
	3.	✔ Documentation: Clear and concise explanations in the code comments make it easy for future contributors to understand. 📄

Suggestions for Improvement:

	1.	✔ Error Handling: It would be beneficial to add more comprehensive error handling, especially when dealing with API requests. This ensures a more robust user experience when network issues arise. 🌐
	2.	✔ Optimization: Consider optimizing some of the components for performance, particularly in rendering large datasets. Using React’s memo or lazy loading where appropriate can improve efficiency. ⚡

Overall, fantastic job! Keep up the great work. 🎉


Marwa Sadat

**Comment by Marwa-Sadat** [comment]
🚀 Excellent Work on the Space Travelers’ Hub!

Hey Shokoofa, 👋

I’ve reviewed this pull request, and I must say, the implementation is impressive! Here are a few highlights:

	1.	✔ Code Quality: The code is well-organized and easy to follow. I appreciate the attention to detail in adhering to the project structure. 🏗
	2.	✔ Functionality: The added features integrate seamlessly with the existing codebase, providing a smooth user experience. The responsiveness is spot-on, especially across different viewports. 📱💻
	3.	✔ Documentation: Clear and concise explanations in the code comments make it easy for future contributors to understand. 📄

Suggestions for Improvement:

	1.	✔ Error Handling: It would be beneficial to add more comprehensive error handling, especially when dealing with API requests. This ensures a more robust user experience when network issues arise. 🌐
	2.	✔ Optimization: Consider optimizing some of the components for performance, particularly in rendering large datasets. Using React’s memo or lazy loading where appropriate can improve efficiency. ⚡

Overall, fantastic job! Keep up the great work. 🎉

Best regards,
Marwa Sadat

**Comment by Marwa-Sadat** [comment]
🚀 Excellent Work on the Space Travelers’ Hub!

Hey Shokoofa, 👋

I’ve reviewed this pull request, and I must say, the implementation is impressive! Here are a few highlights:

	1.	✔ Code Quality: The code is well-organized and easy to follow. I appreciate the attention to detail in adhering to the project structure. 🏗
	2.	✔ Functionality: The added features integrate seamlessly with the existing codebase, providing a smooth user experience. The responsiveness is spot-on, especially across different viewports. 📱💻
	3.	✔ Documentation: Clear and concise explanations in the code comments make it easy for future contributors to understand. 📄

Suggestions for Improvement:

	1.	✔ Error Handling: It would be beneficial to add more comprehensive error handling, especially when dealing with API requests. This ensures a more robust user experience when network issues arise. 🌐
	2.	✔ Optimization: Consider optimizing some of the components for performance, particularly in rendering large datasets. Using React’s memo or lazy loading where appropriate can improve efficiency. ⚡

Overall, fantastic job! Keep up the great work. 🎉

Best regards,
Marwa Sadat

**Comment by Marwa-Sadat** [comment]
🚀 Excellent Work on the Space Travelers’ Hub!

Hey Shokoofa, 👋

I’ve reviewed this pull request, and I must say, the implementation is impressive! Here are a few highlights:

	1.	✔ Code Quality: The code is well-organized and easy to follow. I appreciate the attention to detail in adhering to the project structure. 🏗
	2.	✔ Functionality: The added features integrate seamlessly with the existing codebase, providing a smooth user experience. The responsiveness is spot-on, especially across different viewports. 📱💻
	3.	✔ Documentation: Clear and concise explanations in the code comments make it easy for future contributors to understand. 📄

Suggestions for Improvement:

	1.	✔ Error Handling: It would be beneficial to add more comprehensive error handling, especially when dealing with API requests. This ensures a more robust user experience when network issues arise. 🌐
	2.	✔ Optimization: Consider optimizing some of the components for performance, particularly in rendering large datasets. Using React’s memo or lazy loading where appropriate can improve efficiency. ⚡

Overall, fantastic job! Keep up the great work. 🎉

Best regards,
Marwa Sadat

**Comment by Marwa-Sadat** [comment]
Hi @shogof 🙋‍♀,
Fantastic work! 👏 You’ve nailed all the project requirements. 🎉 Your feature is fully complete! Huge congratulations!!! 🎊
Great Job! The design implementation is amazing. 🏆🎨👍
Status: Approved ✅

Highlights 🌟

	•	🎯 The design implementation is top-notch and visually appealing.
	•	🏗 You’ve set up a professional repository with your project’s name.
	•	🛠 You’ve mastered Gitflow by making the development branch your default and committing your work on a feature branch.
	•	📝 Your commits are well-structured, with clear and meaningful messages.
	•	🔧 You configured the linters correctly according to the language used in the project.
	•	✅ All linters checks passed successfully with no errors.
	•	💻 You followed the Space Travelers’ Hub project instructions and made command-line commits.
	•	🔗 You submitted a pull request for review from your feature branch to the development branch.
	•	📋 You completed all project requirements.
	•	📝 Your pull request description clearly explains the features and improvements introduced.
	•	🧹 The code is clean and well-organized.
	•	📄 Your repository includes a professional README.md file.
	•	📱 The design is fully responsive.
	•	🚀 The rockets list is easy to view and interact with, and the reservation functionality is simple and intuitive.
	•	🛡 The rockets’ status (Reserved/Not Reserved) is clearly indicated, making it easy for users to understand the process.

Cheers 🥂 and happy coding! Feel free to reach out with any questions or comments.

Best regards,
Marwa Sadat

**Comment by Marwa-Sadat** [comment]
Hi @shogof 🙋‍♀,
Excellent work! 💯 You’ve done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!! 🎊
Well Done! Great design implemented. 🎯🎉👍
Status: Approved ✅

Highlights 🌟

	•	🎯 The design implementation is top-notch and visually appealing.
	•	🏗 You’ve set up a professional repository with your project’s name.
	•	🛠 You’ve mastered Gitflow by making the development branch your default and committing your work on a feature branch.
	•	📝 Your commits are well-structured, with clear and meaningful messages.
	•	🔧 You configured the linters correctly according to the language used in the project.
	•	✅ All linter checks passed successfully with no errors.
	•	💻 You followed the Space Travelers’ Hub project instructions and made command-line commits.
	•	🔗 You submitted a pull request for review from your feature branch to the development branch.
	•	📋 You completed all project requirements.
	•	📝 Your pull request description clearly explains the features and improvements introduced.
	•	🧹 The code is clean and well-organized.
	•	📄 Your repository includes a professional README.md file.
	•	📱 The design is fully responsive.
	•	🚀 The rockets list is easy to view and interact with, and the reservation functionality is simple and intuitive.
	•	🛡 The rockets’ status (Reserved/Not Reserved) is clearly indicated, making it easy for users to understand the process.

Cheers 🥂 and happy coding! Feel free to reach out with any questions or comments.

Best regards,
Marwa Sadat

**Comment by Marwa-Sadat** [comment]
Hi @shogof 🙋‍♀️,
Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊
Well Done great design Implemented. 🎯🎉👍
Status: Approved ✅
Highlights 😊
💯 The implementation of a great design is superb.
✔️ You've established a professional repository with your project's name.
✔️ You've mastered Gitflow by making the development branch your default and diligently committingy our work on a feature branch. 🌟
✔️ Add this to ensuring commits are more descriptive and follow a logical sequence.
✔️ Setup the linters correctly (You added the correct linters config into your project according tot he language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Build Space Travelers Hub project task and committed using the command line
✔️ You've initiated the pull request by submitting a link for review from your feature branch to the- development branch.
✔️ You have followed and completed the Space Travelers Hub and all requirements.
✔️ You've enriched your PR with a detailed description highlighting the features and improvementsi ncorporated in this pull request. 📝
✔️ Your code is clean
✔️ Your repo has a professional README.md file
✔️ Your design is responsive
✔️ Users can easily view and interact with the rockets list. The functionality of reserving or canceling a reservation is straightforward and easy to understand.
✔️ The rockets’ status (Reserved/Not Reserved) is clearly visible, ensuring users are aware of their actions and their consequences.
C heers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread ifs omething is not 100% clear.

**Comment by shogof** [comment]
@royajamal @Marwa-Sadat 
Thanks guys Good Luck

**Pull request merged**
